/**
 * Default Color Palettes
 * Predefined color schemes for nodes and edges
 */

import type { ColorPalette } from "../types/base.types";

export const DEFAULT_COLOR_PALETTES: ColorPalette[] = [
  {
    id: "purple",
    name: "Purple",
    description: "Purple color scheme",
    primary: "#a855f7",
    background: "#faf5ff",
    foreground: "#581c87",
    border: "#a855f7",
    muted: "#f3e8ff",
    accent: "#9333ea",
  },
  {
    id: "blue",
    name: "Blue",
    description: "Blue color scheme",
    primary: "#3b82f6",
    background: "#eff6ff",
    foreground: "#1e3a8a",
    border: "#3b82f6",
    muted: "#dbeafe",
    accent: "#2563eb",
  },
  {
    id: "green",
    name: "Green",
    description: "Green color scheme",
    primary: "#22c55e",
    background: "#f0fdf4",
    foreground: "#14532d",
    border: "#22c55e",
    muted: "#dcfce7",
    accent: "#16a34a",
  },
  {
    id: "orange",
    name: "Orange",
    description: "Orange color scheme",
    primary: "#f97316",
    background: "#fff7ed",
    foreground: "#7c2d12",
    border: "#f97316",
    muted: "#ffedd5",
    accent: "#ea580c",
  },
  {
    id: "red",
    name: "Red",
    description: "Red color scheme",
    primary: "#ef4444",
    background: "#fef2f2",
    foreground: "#7f1d1d",
    border: "#ef4444",
    muted: "#fee2e2",
    accent: "#dc2626",
  },
  {
    id: "pink",
    name: "Pink",
    description: "Pink color scheme",
    primary: "#ec4899",
    background: "#fdf2f8",
    foreground: "#831843",
    border: "#ec4899",
    muted: "#fce7f3",
    accent: "#db2777",
  },
  {
    id: "cyan",
    name: "Cyan",
    description: "Cyan color scheme",
    primary: "#06b6d4",
    background: "#ecfeff",
    foreground: "#164e63",
    border: "#06b6d4",
    muted: "#cffafe",
    accent: "#0891b2",
  },
  {
    id: "yellow",
    name: "Yellow",
    description: "Yellow color scheme",
    primary: "#eab308",
    background: "#fefce8",
    foreground: "#713f12",
    border: "#eab308",
    muted: "#fef9c3",
    accent: "#ca8a04",
  },
  {
    id: "gray",
    name: "Gray",
    description: "Gray color scheme",
    primary: "#6b7280",
    background: "#f9fafb",
    foreground: "#111827",
    border: "#6b7280",
    muted: "#f3f4f6",
    accent: "#4b5563",
  },
];
